# Generated by Django 3.2.3 on 2021-09-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slug', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('property_description', models.TextField()),
                ('property_img', models.ImageField(default='default-car.png', upload_to='cars')),
                ('occupation_date', models.DateTimeField(auto_now_add=True)),
                ('prefered_tenant', models.CharField(max_length=200)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('Suburb', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=300)),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.landload')),
            ],
        ),
    ]
