# Generated by Django 3.2.3 on 2021-09-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.suburb'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('INDUSTRIAL', 'INDUSTRIAL'), ('RESIDENTAI', 'RESIDENTAI')], default='INDUSTRIAL', max_length=200),
        ),
    ]
