# Generated by Django 3.2.7 on 2021-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20210927_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bath',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_beds',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('INDUSTRIAL', 'INDUSTRIAL'), ('RESIDENTAI', 'RESIDENTAI'), ('OFFICES', 'OFFICES')], default='RESIDENTAIL', max_length=200),
        ),
    ]
