# Generated by Django 3.2.7 on 2021-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20210930_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
    ]
