# Generated by Django 3.2.7 on 2021-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_property_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('INDUSTRIAL', 'INDUSTRIAL'), ('RESIDENTAIL', 'RESIDENTAIL'), ('OFFICES', 'OFFICES')], default='RESIDENTAIL', max_length=200),
        ),
    ]
