# Generated by Django 3.2.7 on 2021-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
